### ISSUE TITLE
Testimonlials Slider

### ISSUE THREAD

**Issue by stephan-schmidt** [ccmdesign/100-questions-components#11]
Dummy content looks good and Slider works!
http://dev.the100questions.org/partner.html

The css is different from the graphics. I think in the graphic it looks like overlay between two layers

https://xd.adobe.com/view/1f3640db-6c33-44e8-46a8-28c1f4ff1b6f-6907/screen/75c2632e-7fa8-4791-9daf-527e751fef2c/Partners/

**Comment by stephan-schmidt** [comment]
CSS: Quotation Mark is hidden on desktop and double on mobile

See example: 
http://dev.the100questions.org/partner.html

**Comment by arthurbergmz** [comment]
Added workaround because of slider's `overflow: hidden`
