### ISSUE TITLE
Menu - Domain progress bar 

### ISSUE THREAD

**Issue by stephan-schmidt** [ccmdesign/100-questions-components#12]
As far as I can see, they are all reflected, which particular class are you referring too? Attached the compiled CSS currently in use. What class needs a change/ amendment? Please advise. 
[styles.css.zip](https://github.com/ccmdesign/100-questions-components/files/3647364/styles.css.zip)

_Originally posted by @stephan-schmidt in https://github.com/ccmdesign/100-questions-components/issues/5#issuecomment-534554088_

**Comment by arthurbergmz** [comment]
Hello, Stephan.

I've just replaced the code from the the repository into the source code from [dev.the100questions.org](http://dev.the100questions.org) and it worked flawlessly. It is definetely something with your HTML. Try putting a space between the `<li>` tags or a line break among them. Another aproach is removing every space between those `<li>` elements and trying to add this piece of CSS to the code:

```css
.domain-level__mark + .domain-level__mark {
  margin-left: 4px;
}
```
