### ISSUE TITLE
Browser Test: Firefox issues 

### ISSUE THREAD

**Issue by stephan-schmidt** [ccmdesign/100-questions-components#13]
Tested in FF 48.0.2

heaps of CSS issues arose  
http://dev.the100questions.org/

- Staggering of cards
![image](https://user-images.githubusercontent.com/1506096/67041079-d9e62000-f0f2-11e9-9da6-3741496b750a.png)

- Hamburger menu top left does not open 

- Bilinguals staggered -> need grid layout 
![image](https://user-images.githubusercontent.com/1506096/67041167-0dc14580-f0f3-11e9-9c7a-ac9cad5f9276.png)

Partner logos staggered -> need grid layout 
![image](https://user-images.githubusercontent.com/1506096/67041261-419c6b00-f0f3-11e9-9f16-273f27397f13.png)

Same in 
/team.html
/partner.html
/bilinguals.html

**Comment by stephan-schmidt** [comment]
FF 69.0.3 - all works, 
update of FF to newest version in need.

**Comment by claudioccm** [comment]
Closing this, because we won't provide support for old browsers.
