### ISSUE TITLE
Questions: Size and alignment for buttons

### ISSUE THREAD

**Issue by stephan-schmidt** [ccmdesign/100-questions-components#14]
I need a CSS for the read more button also to align right, I see you using     flex: 1; in the parent element. Thanks for support. And I would need a max width based on your grid system.

![image](https://user-images.githubusercontent.com/1506096/67697040-4a583100-f97e-11e9-8ffe-382cbc9dfbb4.png)

Example here: http://dev.the100questions.org/vote_vue.html

**Comment by claudioccm** [comment]
closing this, because this will be addressed in a different issue
