### ISSUE TITLE
Disinformation domain card cuts off

### ISSUE THREAD

**Issue by claudioccm** [ccmdesign/100-questions-components#19]
Disinformation domain card cuts off - title and text is visible, but have to scroll over to the right to see the progress indicator graphic
Found out its the CSS and if the headline or the sub-headline are too long they push out the phase indicator half-circle

- [ ] Make `<h1 class="header-title">DISINFORMATION</h1>` 2.2 rem

**Comment by arthurbergmz** [comment]
Fixed sizing and added support for anchors.
