### ISSUE TITLE
CSS - Domain Card

### ISSUE THREAD

**Issue by stephan-schmidt** [ccmdesign/100-questions-components#2]
Reference: http://dev.the100questions.org/domain-cards.html 
- On Desktop larger space underneath card with less description content.
![image](https://user-images.githubusercontent.com/1506096/61747225-663eac00-ad6b-11e9-8e86-4fe0c1dd1c81.png)

- Partners are displayed in names, the graphics showed the logo
current html DOM `<ul class="domain-card-partner-list"><li>Partner A</li> <li>Partner B</li></ul>` according to the graphics an `<img>` tag is in need with a certain height for all viewports  

see graphic https://xd.adobe.com/view/1f3640db-6c33-44e8-46a8-28c1f4ff1b6f-6907/

**Comment by arthurbergmz** [comment]
- `img` tag added.
- Domain card height fixed.
