### ISSUE TITLE
Domain Link color

### ISSUE THREAD

**Issue by claudioccm** [ccmdesign/100-questions-components#21]
For the intro paragraphs on each domain page, we need a new font color for links -- see https://migration.the100questions.org/ for example. You cannot read “Contact Form” at the end of the paragraph. 

- [x] vamos só fazer o link ficar branco com o underline. 

screencast aqui - https://drive.google.com/a/ccmdesign.ca/file/d/185Rricu957I7v87fUnNBz1L5CWHbUwOM/view?usp=drivesdk

<img width="1048" alt="Screen Shot 2019-11-25 at 16 50 33" src="https://user-images.githubusercontent.com/1649373/69590245-b3de5600-0fa3-11ea-92dd-ffb9089c421e.png">

**Comment by arthurbergmz** [comment]
Added support for anchors in header texts in the last commit.
