### ISSUE TITLE
Weird Line Breaks

### ISSUE THREAD

**Issue by claudioccm** [ccmdesign/100-questions-components#22]
- [ ] Vamos só eliminar essas quebras de linhas. Estamos usando uma quebra de linha hard coded na pagina de about.

<img width="444" alt="Screen Shot 2019-11-25 at 16 52 30" src="https://user-images.githubusercontent.com/1649373/69590342-03bd1d00-0fa4-11ea-902d-090860e32a71.png">
<img width="443" alt="Screen Shot 2019-11-25 at 16 52 59" src="https://user-images.githubusercontent.com/1649373/69590360-10da0c00-0fa4-11ea-893f-862b612c2c02.png">

**Comment by arthurbergmz** [comment]
Can't erase breaklines due to container width... :/

**Comment by arthurbergmz** [comment]
Maybe lowering font size?
