### ISSUE TITLE
About - Left spacing

### ISSUE THREAD

**Issue by claudioccm** [ccmdesign/100-questions-components#23]
- [x] espaço estranho na esquerda
- [x] Team section está renderizando meio estranho

<img width="444" alt="Screen Shot 2019-11-25 at 16 52 30" src="https://user-images.githubusercontent.com/1649373/69590651-04a27e80-0fa5-11ea-9cd1-c8da27fc56e2.png">
<img width="443" alt="Screen Shot 2019-11-25 at 16 52 59" src="https://user-images.githubusercontent.com/1649373/69590652-04a27e80-0fa5-11ea-96ce-677d4e6471f8.png">
<img width="492" alt="Screen Shot 2019-11-25 at 16 57 43" src="https://user-images.githubusercontent.com/1649373/69590653-04a27e80-0fa5-11ea-92a1-bef5b51f6e96.png">
<img width="491" alt="Screen Shot 2019-11-25 at 16 57 49" src="https://user-images.githubusercontent.com/1649373/69590654-04a27e80-0fa5-11ea-8532-32bf4119aa47.png">

**Comment by arthurbergmz** [comment]
Wrong implementation from the old website. Maybe there are conflicting classes?

Original version:
http://100-questions-original-about.s3-website-us-east-1.amazonaws.com/
