### ISSUE TITLE
Menu - Domain progress bar

### ISSUE THREAD

**Issue by stephan-schmidt** [ccmdesign/100-questions-components#5]
The progress bar CSS when loaded dynamically has a wider gap between the yellow and the white bars. When the list elements are in there static, everything looks good. Maybe some css is applied differently after a dynamic load of the document?

![image](https://user-images.githubusercontent.com/1506096/62251103-b5fd2300-b3bc-11e9-96e2-a0437c0ee54f.png)

**Comment by arthurbergmz** [comment]
This happens because of different CSS Reset approaches. Make sure to use the one used on the project.

**Comment by stephan-schmidt** [comment]
Thanks! Please point out the reset parts for the progress bar in the CSS. I didn’t change anything from the original script.

**Comment by arthurbergmz** [comment]
_base.scss

**Comment by stephan-schmidt** [comment]
As far as I can see, they are all reflected, which particular class are you referring too? Attached the compiled CSS currently in use. What class needs a change/ amendment? Please advise. 
[styles.css.zip](https://github.com/ccmdesign/100-questions-components/files/3647364/styles.css.zip)
