### ISSUE TITLE
Domain - description length

### ISSUE THREAD

**Issue by stephan-schmidt** [ccmdesign/100-questions-components#9]
If the description is too long, the "questions" bar is pushed down
http://dev.the100questions.org/domain.html

Long text: 
![image](https://user-images.githubusercontent.com/1506096/62497949-8464cd00-b7ab-11e9-8b3f-5ff2fbf92322.png)

Short Text:  
![image](https://user-images.githubusercontent.com/1506096/62497981-a65e4f80-b7ab-11e9-8980-e6556cc9b995.png)

**Comment by arthurbergmz** [comment]
This is just the zoom feature on PC, not a real device-resolution issue, since this visual tweak is happening because of proper adaptations to mobile devices.
